import hashlib
import logging
import uuid
from collections import defaultdict
from dataclasses import dataclass
from datetime import date, datetime, time, timedelta
from typing import Any, Mapping

from sqlalchemy import func, select, text
from sqlalchemy.ext.asyncio import AsyncSession

from models import Booking, TimeSlot

logger = logging.getLogger("booking_service")

ACTIVE_BOOKING_STATUSES = ("pending", "confirmed")
BOOKING_STATUSES = (
    "pending",
    "confirmed",
    "cancelled",
    "rescheduled",
    "completed",
)


class BookingServiceError(Exception):
    """Base class for expected booking domain failures."""


class BookingValidationError(BookingServiceError):
    """Raised when a booking mutation contains invalid domain data."""


class BookingSlotUnavailable(BookingServiceError):
    """Raised when the requested time is not generated by any active schedule."""


class BookingSlotFull(BookingServiceError):
    """Raised when the requested slot has no remaining capacity."""


class BookingNotFound(BookingServiceError):
    """Raised when a tenant-scoped booking cannot be found."""


@dataclass(frozen=True)
class BookingSlotAvailability:
    time: time
    remaining: int


def _booking_slot_lock_key(
    user_id: uuid.UUID, booking_date: date, booking_time: time
) -> str:
    return f"booking-slot:{user_id}:{booking_date.isoformat()}:{booking_time.isoformat()}"


def _booking_slot_advisory_lock_id(
    user_id: uuid.UUID, booking_date: date, booking_time: time
) -> int:
    key = _booking_slot_lock_key(user_id, booking_date, booking_time)
    digest = hashlib.blake2b(key.encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(digest, byteorder="big", signed=True)


async def _acquire_booking_slot_lock(
    db: AsyncSession, user_id: uuid.UUID, booking_date: date, booking_time: time
) -> None:
    bind = db.get_bind()
    if bind is None or bind.dialect.name != "postgresql":
        return

    lock_id = _booking_slot_advisory_lock_id(user_id, booking_date, booking_time)
    await db.execute(
        text("SELECT pg_advisory_xact_lock(:lock_id)"),
        {"lock_id": lock_id},
    )


def _slot_contains_booking_time(
    slot: TimeSlot, booking_date: date, booking_time: time
) -> bool:
    duration_seconds = int(timedelta(minutes=slot.slot_duration_minutes).total_seconds())
    if duration_seconds <= 0:
        return False

    start = datetime.combine(booking_date, slot.start_time)
    requested = datetime.combine(booking_date, booking_time)
    end = datetime.combine(booking_date, slot.end_time)
    if requested < start or requested + timedelta(seconds=duration_seconds) > end:
        return False

    offset_seconds = int((requested - start).total_seconds())
    return offset_seconds % duration_seconds == 0


def _iter_slot_times(slot: TimeSlot, target_date: date):
    duration = timedelta(minutes=slot.slot_duration_minutes)
    if duration.total_seconds() <= 0:
        return

    current = datetime.combine(target_date, slot.start_time)
    end = datetime.combine(target_date, slot.end_time)
    while current + duration <= end:
        yield current.time()
        current += duration


async def _locked_matching_slots(
    db: AsyncSession, user_id: uuid.UUID, booking_date: date, booking_time: time
) -> list[TimeSlot]:
    stmt = (
        select(TimeSlot)
        .where(
            TimeSlot.user_id == user_id,
            TimeSlot.day_of_week == booking_date.weekday(),
            TimeSlot.start_time <= booking_time,
            TimeSlot.end_time > booking_time,
            TimeSlot.is_active.is_(True),
        )
        .order_by(TimeSlot.start_time, TimeSlot.id)
        .with_for_update()
    )
    slots = list((await db.execute(stmt)).scalars().all())
    return [
        slot for slot in slots if _slot_contains_booking_time(slot, booking_date, booking_time)
    ]


async def _count_active_bookings(
    db: AsyncSession,
    user_id: uuid.UUID,
    booking_date: date,
    booking_time: time,
    *,
    exclude_booking_id: uuid.UUID | None = None,
) -> int:
    stmt = select(func.count()).where(
        Booking.user_id == user_id,
        Booking.booking_date == booking_date,
        Booking.booking_time == booking_time,
        Booking.status.in_(ACTIVE_BOOKING_STATUSES),
    )
    if exclude_booking_id is not None:
        stmt = stmt.where(Booking.id != exclude_booking_id)
    return int((await db.execute(stmt)).scalar() or 0)


def _capacity_for_slots(slots: list[TimeSlot]) -> int:
    return sum(max(slot.max_bookings_per_slot or 0, 0) for slot in slots)


async def _assert_slot_capacity(
    db: AsyncSession,
    *,
    user_id: uuid.UUID,
    booking_date: date,
    booking_time: time,
    exclude_booking_id: uuid.UUID | None = None,
) -> None:
    await _acquire_booking_slot_lock(db, user_id, booking_date, booking_time)
    matching_slots = await _locked_matching_slots(db, user_id, booking_date, booking_time)
    if not matching_slots:
        logger.info(
            "booking_slot_unavailable user_id=%s date=%s time=%s",
            user_id,
            booking_date,
            booking_time,
        )
        raise BookingSlotUnavailable("The requested time is outside available business hours.")

    capacity = _capacity_for_slots(matching_slots)
    existing_count = await _count_active_bookings(
        db,
        user_id,
        booking_date,
        booking_time,
        exclude_booking_id=exclude_booking_id,
    )
    if existing_count >= capacity:
        logger.info(
            "booking_slot_full user_id=%s date=%s time=%s existing=%s capacity=%s",
            user_id,
            booking_date,
            booking_time,
            existing_count,
            capacity,
        )
        raise BookingSlotFull(
            "Sorry, this time slot is already fully booked. Please choose another time."
        )


async def create_booking_atomic(
    db: AsyncSession,
    *,
    user_id: uuid.UUID,
    customer_name: str,
    booking_date: date,
    booking_time: time,
    session_id: uuid.UUID | None = None,
    customer_phone: str | None = None,
    service_name: str | None = None,
    notes: str | None = None,
    status: str = "pending",
) -> Booking:
    if status not in BOOKING_STATUSES:
        raise BookingValidationError(f"Unsupported booking status: {status}")
    if not customer_name.strip():
        raise BookingValidationError("Customer name is required.")

    try:
        if status in ACTIVE_BOOKING_STATUSES:
            await _assert_slot_capacity(
                db,
                user_id=user_id,
                booking_date=booking_date,
                booking_time=booking_time,
            )

        booking = Booking(
            user_id=user_id,
            session_id=session_id,
            customer_name=customer_name.strip(),
            customer_phone=customer_phone,
            service_name=service_name,
            booking_date=booking_date,
            booking_time=booking_time,
            status=status,
            notes=notes,
        )
        db.add(booking)
        await db.commit()
        await db.refresh(booking)
        logger.info(
            "booking_created user_id=%s booking_id=%s date=%s time=%s status=%s",
            user_id,
            booking.id,
            booking.booking_date,
            booking.booking_time,
            booking.status,
        )
        return booking
    except BookingServiceError:
        await db.rollback()
        raise
    except Exception:
        await db.rollback()
        logger.exception(
            "booking_create_failed user_id=%s date=%s time=%s",
            user_id,
            booking_date,
            booking_time,
        )
        raise


async def update_booking_atomic(
    db: AsyncSession,
    *,
    user_id: uuid.UUID,
    booking_id: uuid.UUID,
    updates: Mapping[str, Any],
) -> Booking:
    changes = dict(updates)

    try:
        result = await db.execute(
            select(Booking)
            .where(Booking.id == booking_id, Booking.user_id == user_id)
            .with_for_update()
        )
        booking = result.scalar_one_or_none()
        if booking is None:
            raise BookingNotFound("Booking not found")

        target_status = changes.get("status", booking.status)
        if target_status not in BOOKING_STATUSES:
            raise BookingValidationError(f"Unsupported booking status: {target_status}")

        target_date = changes.get("booking_date", booking.booking_date)
        target_time = changes.get("booking_time", booking.booking_time)
        needs_capacity_check = target_status in ACTIVE_BOOKING_STATUSES and (
            target_date != booking.booking_date
            or target_time != booking.booking_time
            or booking.status not in ACTIVE_BOOKING_STATUSES
        )

        if needs_capacity_check:
            await _assert_slot_capacity(
                db,
                user_id=booking.user_id,
                booking_date=target_date,
                booking_time=target_time,
                exclude_booking_id=booking.id,
            )

        for field, value in changes.items():
            setattr(booking, field, value)

        await db.commit()
        await db.refresh(booking)
        logger.info(
            "booking_updated user_id=%s booking_id=%s date=%s time=%s status=%s",
            booking.user_id,
            booking.id,
            booking.booking_date,
            booking.booking_time,
            booking.status,
        )
        return booking
    except BookingServiceError:
        await db.rollback()
        raise
    except Exception:
        await db.rollback()
        logger.exception("booking_update_failed booking_id=%s", booking_id)
        raise


async def list_available_booking_slots(
    db: AsyncSession, user_id: uuid.UUID, target_date: date
) -> list[BookingSlotAvailability]:
    result = await db.execute(
        select(TimeSlot).where(
            TimeSlot.user_id == user_id,
            TimeSlot.day_of_week == target_date.weekday(),
            TimeSlot.is_active.is_(True),
        )
    )
    slots = list(result.scalars().all())
    capacity_by_time: dict[time, int] = defaultdict(int)
    for slot in slots:
        for slot_time in _iter_slot_times(slot, target_date) or ():
            capacity_by_time[slot_time] += max(slot.max_bookings_per_slot or 0, 0)

    if not capacity_by_time:
        return []

    booked_result = await db.execute(
        select(Booking.booking_time, func.count())
        .where(
            Booking.user_id == user_id,
            Booking.booking_date == target_date,
            Booking.status.in_(ACTIVE_BOOKING_STATUSES),
        )
        .group_by(Booking.booking_time)
    )
    booked = {slot_time: int(count) for slot_time, count in booked_result.all()}

    available = []
    for slot_time in sorted(capacity_by_time):
        remaining = capacity_by_time[slot_time] - booked.get(slot_time, 0)
        if remaining > 0:
            available.append(BookingSlotAvailability(time=slot_time, remaining=remaining))
    return available
