import logging
from typing import Optional
from openai import AsyncOpenAI
import json

logger = logging.getLogger("humanizer_agent")

HUMANIZER_SYSTEM_PROMPT = """You are the Humanizer Agent for a customer support chat.
Your ONLY job is to take a draft message and rewrite it into a hyper-realistic, casual WhatsApp message.
You must act exactly like a real human employee texting.

## INPUT
You will receive:
1. style_samples: Examples of how the business actually talks.
2. user_voice_settings: JSON describing the desired dialect, tone, and emoji usage.
3. logic_draft: The factual message generated by the Knowledge Agent.

## RULES (CRITICAL):
1. **NO FACTUAL CHANGES:** You MUST keep all prices, numbers, product names, and core facts EXACTLY as they appear in the logic_draft. If the draft says a product is out of stock, your rewrite must say it's out of stock. If it says 50 JOD, you must say 50 JOD.
2. **LAZY TYPING:** NEVER use periods (.) or commas (,) at the end of sentences. Humans don't use punctuation on WhatsApp.
3. **MULTI-BUBBLE FORMAT:** If you need to say multiple things, separate them with an actual line break (press Enter). Do not write the literal characters '\\n'.
   Example:
   هلا أخوي
   ثواني أشوفلك إياه
4. **NO ROBOTIC BOILERPLATE:** NEVER say "How can I help you?". NEVER use bullet points. NEVER use bold text (**).
5. **SLANG & FILLERS:** Use filler words ("شوف", "والله", "أكيد") matching the dialect. If the draft is in formal Arabic, you MUST convert it to the requested dialect.
6. **NO INTRODUCTIONS:** Just output the rewritten text directly. Do not say "Here is the rewritten text".

## OUTPUT:
Just output the raw string text that will be sent to the customer.
"""

class HumanizerAgent:
    """Rewrites AI drafts into human-like WhatsApp messages."""

    def __init__(self, api_key: str):
        self._client = AsyncOpenAI(api_key=api_key)

    async def rewrite(
        self,
        logic_draft: str,
        style_samples: list[str],
        voice_settings: dict,
    ) -> str:
        """
        Takes the factual logic draft and rewrites it according to the persona and style samples.
        """
        
        # If the draft is a simple tool request (shouldn't happen here usually) or empty, just return it
        if not logic_draft or logic_draft.strip() == "":
            return logic_draft

        # Prepare the input payload
        joined_samples = "\\n---\\n".join(style_samples[:5]) if style_samples else "No samples provided. Use casual generic Arabic."
        
        user_prompt = (
            f"**style_samples:**\\n{joined_samples}\\n\\n"
            f"**user_voice_settings:**\\n{json.dumps(voice_settings, ensure_ascii=False)}\\n\\n"
            f"**logic_draft (Rewrite this):**\\n{logic_draft}"
        )

        try:
            response = await self._client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": HUMANIZER_SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.8, # High temperature for maximum creativity in phrasing
                max_tokens=300,
            )
            
            rewritten_text = response.choices[0].message.content or logic_draft
            return rewritten_text.strip()
            
        except Exception as e:
            logger.error(f"Humanizer Agent failed: {e}")
            return logic_draft # Fallback to the logic draft if the rewrite fails
